# Generated by Django 5.0.6 on 2024-06-02 04:12

import django.db.models.deletion
import shortuuidfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0005_alter_movie_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, help_text='用户ID', max_length=22, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('phone', models.CharField(blank=True, help_text='手机号码', max_length=20, null=True, unique=True, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=255, null=True, unique=True, verbose_name='邮箱')),
                ('avatar', models.ImageField(blank=True, help_text='头像', null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='头像')),
                ('is_upgrade', models.BooleanField(default=False, help_text='是否升级为会员', verbose_name='是否升级为会员')),
                ('upgrade_time', models.DateTimeField(blank=True, help_text='升级时间', null=True, verbose_name='升级时间')),
                ('expire_time', models.DateTimeField(blank=True, help_text='到期时间', null=True, verbose_name='到期时间')),
                ('upgrade_count', models.IntegerField(default=0, help_text='升级次数', verbose_name='升级次数')),
                ('movies', models.ManyToManyField(blank=True, help_text='收藏电影', related_name='profiles', to='movie.movie', verbose_name='收藏电影')),
                ('user', models.OneToOneField(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
