# Generated by Django 5.0.6 on 2024-06-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('ALIPAY', '支付宝'), ('WECHAT', '微信'), ('UNIONPAY', '银联')], default='ALIPAY', help_text='支付类型', max_length=20, verbose_name='支付类型'),
        ),
    ]
