# Generated by Django 5.0.6 on 2024-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_order_pay_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '交易成功'), ('TRADE_CLOSED', '交易关闭'), ('WAIT_BUYER_PAY', '等待买家付款'), ('TRADE_FINISHED', '交易结束'), ('TRADE_FAIL', '交易失败')], default='WAIT_BUYER_PAY', help_text='支付状态', max_length=20, verbose_name='支付状态'),
        ),
    ]
