# Generated by Django 5.0.6 on 2024-05-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '分类管理',
                'verbose_name_plural': '分类管理',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('release_year', models.IntegerField(verbose_name='上映年份')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('scriptwriter', models.CharField(max_length=100, verbose_name='编剧')),
                ('actor', models.CharField(max_length=100, verbose_name='主演')),
                ('region', models.SmallIntegerField(choices=[(1, '中国'), (2, '美国'), (3, '日本'), (4, '韩国'), (5, '英国'), (6, '法国'), (7, '德国'), (8, '其他')], verbose_name='地区')),
                ('types', models.CharField(max_length=100, verbose_name='类型')),
                ('language', models.CharField(max_length=100, verbose_name='语言')),
                ('release_date', models.DateField(verbose_name='上映日期')),
                ('duration', models.IntegerField(verbose_name='片长')),
                ('alternate_name', models.CharField(max_length=100, verbose_name='又名')),
                ('image_url', models.URLField(verbose_name='海报链接')),
                ('rate', models.FloatField(verbose_name='评分')),
                ('review', models.TextField(verbose_name='简介')),
                ('is_hot', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否热门')),
                ('is_top', models.BooleanField(choices=[(True, '是'), (False, '否')], default=False, verbose_name='是否置顶')),
                ('quality', models.SmallIntegerField(choices=[(1, '高清'), (2, '超清'), (3, '蓝光')], verbose_name='画质')),
                ('subtitle', models.CharField(max_length=100, verbose_name='字幕')),
                ('update_info', models.CharField(max_length=100, verbose_name='更新信息')),
                ('update_progress', models.CharField(max_length=100, verbose_name='更新进度')),
                ('download_info', models.CharField(help_text='格式：链接+密码', max_length=500, verbose_name='网盘链接')),
                ('is_show', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否显示')),
                ('is_free', models.BooleanField(choices=[(True, '是'), (False, '否')], default=True, verbose_name='是否免费')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.category', verbose_name='电影分类')),
            ],
            options={
                'verbose_name': '电影管理',
                'verbose_name_plural': '电影管理',
            },
        ),
    ]
