# Generated by Django 5.0.6 on 2024-05-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_category_options_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': '电影', 'verbose_name_plural': '电影'},
        ),
    ]
