# Generated by Django 5.0.6 on 2024-05-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_actor_movie_actors_remove_movie_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=100, verbose_name='片长'),
        ),
    ]
